### ISSUE TITLE
Add support for deregistered products

### ISSUE THREAD

**Issue by ephaee** [epha/robot#1]

**Comment by topa** [comment]
I assume this issue is related to the swissmedic-history-topic I've discussed with @Jonas74 today.

The idea was to create some kind of history or rather a register with all products from swissmedic - also containing discontinued/de-registered products.

It should work like this:

1. The first release of swissmedic.json will be used as base for the history.
2.  After a run of swissmedic-job there will be a contents comparison.
  - If there is an entry missing in the "new" release it will be flagged as *de-registered* in the *history*.
  - flag should be the date of de-registration 
  - If there is a new entry in the "new" release it will be get a recored in history
3. If history was wiped/delete it starts again with 1.

@Jonas74 is this correct? Is there something missing?

Some questions:

- Does a new release of swissmedic.json contain de-registered entries?
- Or is a new release a merge of current and old data?

**Comment by topa** [comment]
## Swissmedic History Concept

### Pre-Steps

1. download XLSX
2. parse Swissmedic XSLX
3. write Swissmedic JSON

### Building History File

1. check if History is present
2. History **is** present
  1. read history file (JSON containing a huge Array [~17500 entries])
  2. create a in-memory key-value store from history (history-store) with **GTIN** as key 
  3. create a in-memory key-value store from *pre-steps* (tmp) JSON with **GTIN** as key
  4. iterate over history-store and access tmp's data by using **GTIN**-key 
     1. data is accessible 
         1. copy data from *tmp* to history
         2. delete processed data from *tmp*    
     2. data is in-accessible
         1. flag data from history as de-registered (e.g. add a date)   
  5. iterate over new-store's left data (= new entries)
     1. copy new entries to history    
3. History **is not** present
    1. Use *tmp* as history

**Comment by topa** [comment]
@meaku suggested to take a closer look at [dat-data.com](dat-data.com). If I understood him right dat supports reproducible or rather version-ed data.

**Comment by topa** [comment]
I think this feature is implemented so far. It writes three different types of logs:

## new

`logs/swissmedic/swissmedic.history.new.log`:

```
02.06.2015|GTIN:321321321321321
```

## de-registered

`logs/swissmedic/swissmedic.history.deRegistered.log`:

```
02.06.2015|GTIN:7680002780013
```

A de-registered product will look like this in history-file:

```json
 {
      "zulassung": "00278",
      "sequenz": "1",
      "name": "Colon Sérocytol, suppositoire",
      "hersteller": "Sérolab, société anonyme",
      "itnummer": "08.07.",
      "atc": "J06AA",
      // ...
      "gtin": "7680002780013",
      "deregistered": "02.6.2015"
   },
```

## changes

`logs/swissmedic/swissmedic.history.changes`:

```
02.06.2015|GTIN:7680002770014|{"zulassung":["00277","changed"]}
```

You can see which product has changed by GTIN and what exactly has changed: 

```json
{"key": ["previous-value", "new-value"], "anotherKey": ["previous-value", "new-value"]}.
```

## open questions

- Is it possible that a de-registered product will be re-registered?
- There aren't any information about prices. Where to get them?

@Jonas74 are you fine with this?
