### ISSUE TITLE
Kompendium

### ISSUE THREAD

**Issue by Jonas74** [epha/robot#20]
Remove jsdom, if you don't need it.

**Comment by topa** [comment]
If you compare the [old](https://github.com/epha/robot/blob/master/jobs/kompendium.js#L89) code with the [new](https://github.com/epha/robot/blob/refactoring-step-1/lib/kompendium/acceptTermsOfUse.js#L14) one you can see that jsdom is basically used as the RegExps. It 
parses the HTML for the hidden inputs field. 
But in my opinion it is more reliable and easier to understand what is going when using  ```document.querySelector``` instead of RegExps. 
Maybe it is in the end a matter of taste how to solve this task.
I'll change it if you still prefer the RexExp-way.

**Comment by topa** [comment]
I'll close this one. If we need further discussion we can just re-open it.
