### ISSUE TITLE
Superagent

### ISSUE THREAD

**Issue by Jonas74** [epha/robot#21]
We discussed to use request. If request can't do the job, it is fine.

**Comment by topa** [comment]
Superagent has at least on quirk: [kompendium/startDownload](https://github.com/epha/robot/blob/refactoring-step-1/lib/kompendium/startDownload.js#L46). You can see there that the passed response is not streamable. You have to use ```res.res``` that points to the "native"-IncomingMessage which is streamable.
At the moment Superagent is fine. If we use request in other project we should use request instead of superagent, but give this a low prio. At least until we find another quirk.
